name: "Haddock documentation"

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  haddocks:
    name: "Haddocks"

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        ghc: ["9.2.7"]
        os: [ubuntu-latest]

    env:
      CABAL_BUILDDIR: "dist-newstyle"

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout ouroboros-network repository
      uses: actions/checkout@v3

      # we need nix to later build the spec documents
    - name: Install Nix
      uses: cachix/install-nix-action@v20

    - name: Install Haskell
      uses: haskell/actions/setup@v2
      id: setup-haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.10.1.0'

    - uses: actions/cache@v3
      name: Cache cabal store
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: cache-haddock-${{ runner.os }}-${{ matrix.ghc }}-v1-${{ hashFiles('cabal-cache.cabal') }}-${{ github.sha }}
        restore-keys: cache-haddock-${{ runner.os }}-${{ matrix.ghc }}-v1-${{ hashFiles('cabal-cache.cabal') }}-

    - name: Update Hackage index
      run: cabal update

    - name: Build plan
      run: cabal --builddir="$CABAL_BUILDDIR" build --dry-run --enable-tests all

    - name: Build Haddock documentation 🔧
      run: |
        mkdir ./haddocks
        ./scripts/haddocs.sh ./haddocks

    - name: Build documents
      run: |
        for res in $(nix-build -A network-docs); do
          for pdf in $res/*.pdf; do
            PDF_DIR=haddocks/pdfs/$(basename $pdf .pdf)
            mkdir -p $PDF_DIR
            echo '<!DOCTYPE html>' > $PDF_DIR/index.html
            echo -n '<!DOCTYPE html><meta http-equiv="refresh" content="0; URL=' >> $PDF_DIR/index.html
            echo -n $(basename $pdf) >> $PDF_DIR/index.html
            echo '">' >> $PDF_DIR/index.html
            cp $pdf $PDF_DIR/
          done
        done

    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./haddocks

    - name: Deploy 🚀
      id: deployment
      uses: actions/deploy-pages@v2
